@EventGateway.Api_HostAddress = http://localhost:5083

GET {{EventGateway.Api_HostAddress}}/health
Accept: application/json

###

POST {{EventGateway.Api_HostAddress}}/events
Content-Type: application/json

{
  "eventId": "00000000-0000-0000-0000-000000000001",
  "accountId": "acct-123",
  "type": "CREDIT",
  "amount": 150.00,
  "currency": "USD",
  "eventTimestamp": "2026-05-15T14:02:11Z",
  "metadata": {
    "source": "mainframe-batch",
    "batchId": "B-9042"
  }
}

###

GET {{EventGateway.Api_HostAddress}}/events/00000000-0000-0000-0000-000000000001
Accept: application/json

###

GET {{EventGateway.Api_HostAddress}}/events?account=acct-123
Accept: application/json

###

GET {{EventGateway.Api_HostAddress}}/accounts/acct-123/balance
Accept: application/json

###
